// ─── Roles / Experience ────────────────────────────────────────────────────

export const roles = [
  {
    org: "Social Embeddedness, Arizona State University",
    role: "Data Input Specialist",
    period: "May 2026 - Present",
    location: "Tempe, Arizona",
    logo: "/ASU logo.png",
    chapter: "01 / Where I am now",
    lead: "I turn Collaboratory exports into reporting systems people can rely on.",
    bullets: [
      "Built and maintained a Python ETL pipeline that turns raw Collaboratory exports into clean Tableau-ready tables, bridge tables, validation reports, and archived refreshes.",
      "Modeled activity, organization, profile, unit, and course data into relational datasets for Social Embeddedness reporting and interactive dashboards.",
      "Created Tableau dashboards and data model guidance so stakeholders can answer questions, spot patterns, and refresh reports with confidence.",
      "Supported data collection, maintenance, and training with clear definitions, quality checks, and documented reporting processes.",
    ],
    tags: ["Python ETL", "Tableau", "Data modeling", "Documentation"],
  },
  {
    org: "Hitachi Digital Services",
    role: "Data Analyst Associate",
    period: "Aug 2022 - Aug 2025",
    location: "Bengaluru, India",
    logo: "/Hitachi-Logo.png",
    chapter: "02 / Learning at scale",
    lead: "I helped global teams see their operational data more clearly and act on it sooner.",
    bullets: [
      "Designed and maintained Power BI dashboards for QEI and audit KPIs, helping raise process efficiency by 30%.",
      "Prepared, cleaned, and analyzed large datasets with Python, SQL, and Excel to keep compliance and operational health visible.",
      "Built practical Excel tools with PivotTables, Power Query, and validation so recurring reports stayed consistent.",
      "Used regression and trend analysis on global quality audit data, reducing non-compliance prediction errors by 20%.",
      "Automated recurring reports and email distribution with Power Automate, making updates easier to share across stakeholders.",
      "Translated audit requirements into dashboard specs and monthly leadership reports that made the next step clearer.",
    ],
    tags: [],
  },
  {
    org: "Indian Institute of Science",
    role: "Data Science Intern",
    period: "Jan 2022 - Jul 2022",
    location: "Bengaluru, India",
    logo: "/IISC logo.svg",
    chapter: "03 / Where it started",
    lead: "This is where I learned that careful data preparation can turn observation into discovery.",
    bullets: [
      "Developed a ball-tracking application using smartphone video capture and annotated data pipelines for model training.",
      "Created Python visualizations with Matplotlib and Seaborn to explore trajectory performance in a more intuitive way.",
      "Prepared, cleaned, and validated data to improve the model's reliability and consistency.",
      "Used exploratory analysis to uncover patterns in motion data and guide model improvements.",
      "Documented the method, findings, and recommendations so research stakeholders could follow the work.",
    ],
    tags: [],
  },
];

// ─── Skills ────────────────────────────────────────────────────────────────

export const skills = [
  { name: "Python", category: "Programming", desc: "My go-to for ETL pipelines, data checks, and dependable automation." },
  { name: "SQL", category: "Programming", desc: "How I ask large datasets focused questions and shape the answers." },
  { name: "Java", category: "Programming", desc: "Used to build backend services and data-processing applications." },
  { name: "JavaScript", category: "Programming", desc: "Used to create interactive web features and dashboards." },
  { name: "Tableau", category: "Visualization", desc: "Where I turn prepared data into dashboards people can explore on their own." },
  { name: "Power BI", category: "Visualization", desc: "Used to make healthcare and financial analytics easier to see and act on." },
  { name: "Looker Studio", category: "Visualization", desc: "Used to deliver business dashboards from BigQuery data models." },
  { name: "Airflow", category: "Data Engineering", desc: "Keeps scheduled ETL pipelines moving across cloud systems." },
  { name: "PySpark", category: "Data Engineering", desc: "Used when a dataset is large enough to need distributed processing." },
  { name: "ETL", category: "Data Engineering", desc: "The repeatable path from raw source data to useful reporting tables." },
  { name: "Snowflake", category: "Database", desc: "For storing and querying analytical data at scale." },
  { name: "PostgreSQL", category: "Database", desc: "For thoughtful relational data design and complex queries." },
  { name: "Azure", category: "Cloud & DevOps", desc: "Used to deploy pipelines and services through Azure Data Factory." },
  { name: "Git", category: "Cloud & DevOps", desc: "How I keep work traceable and collaborate without losing context." },
  { name: "Power Automate", category: "Data Engineering", desc: "Used to take recurring reporting and stakeholder updates off the manual to-do list." },
  { name: "Excel", category: "Visualization", desc: "Still one of the best places for clear PivotTable reports and Power Query models." },
];

export const skillCategories = ["All", "Programming", "Visualization", "Data Engineering", "Database", "Cloud & DevOps"] as const;
export type SkillCategory = typeof skillCategories[number];

// ─── Education ─────────────────────────────────────────────────────────────

export const education = [
  {
    logo: "/ASU logo.png",
    name: "Arizona State University",
    degree: "Master of Science",
    field: "Computer Science",
    location: "Tempe, Arizona",
    period: "Aug 2025 - May 2027",
    status: "In Progress",
  },
  {
    logo: "/Dr AIT logo.jpeg",
    name: "Dr. Ambedkar Institute Of Technology",
    degree: "Bachelor of Engineering",
    field: "Computer Science",
    location: "Bengaluru, India",
    period: "Aug 2018 - Aug 2022",
    status: "Graduated",
  },
];

// ─── Projects ──────────────────────────────────────────────────────────────

export const projects = [
  {
    slug: "strategic-foresight-toolkit",
    number: "01",
    title: "Strategic Foresight Toolkit Design",
    org: "Global Futures Laboratory · Riipen",
    date: "August 2026",
    feedback: "5.0 feedback",
    teaser: "I translated complex foresight ideas into an inviting, workshop-ready toolkit.",
    lead: "The material already had depth. My job was to give it a visual language that felt welcoming, cohesive, and useful without losing its intellectual weight.",
    collaboratedWith: "Global Futures Laboratory",
    guidedBy: "Bea Rodriguez-Fransen",
    rating: "5.0 overall rating",
    approach: "I built a visual identity around ASU color, typography, and icons, then created flexible layouts for both print and digital settings.",
    deliverables: "Visual identity guidance, print-ready layouts, digital toolkit files, and diagram and visual-metaphor assets ready for use.",
    process: [
      { label: "LISTEN FOR THE CORE", body: "I start by finding the idea, decision, or relationship at the heart of research-heavy content." },
      { label: "GIVE IT A SHAPE", body: "I group the ideas into a clear hierarchy that someone can take in without getting lost." },
      { label: "MAKE RELATIONSHIPS VISIBLE", body: "I use modular layouts, diagrams, and visual metaphors to replace dense blocks of text." },
      { label: "MAKE IT HOLD TOGETHER", body: "I use consistent color, typography, and formats so the toolkit works wherever people encounter it." },
    ],
    skills: ["Functional requirements", "Color palette", "Canva", "Digital data", "Typography", "Usability", "Research"],
    certificate: "/certificates/riipen-strategic-foresight-toolkit.pdf",
    quote: {
      text: "\u201CSanjay excelled in communicating and working efficiently, took initiative beyond the deliverables, and created two toolkit versions well before the deadline.\u201D",
      author: "Bea Rodriguez-Fransen, Assistant Research Professor, Principled Innovation",
    },
  },
  {
    slug: "asu-etl-pipeline",
    number: "02",
    title: "Collaboratory ETL & Tableau Reporting System",
    org: "Social Embeddedness · Arizona State University",
    date: "2026",
    feedback: "Production",
    teaser: "A Python ETL pipeline that transforms messy Collaboratory exports into stakeholder-ready Tableau dashboards.",
    lead: "Raw Collaboratory data arrived in inconsistent exports. I built a pipeline that cleans, validates, and models it into a reporting layer that stakeholders can trust and refresh without my help.",
    collaboratedWith: "Social Embeddedness Lab, ASU",
    guidedBy: "ASU Research Team",
    rating: "Production system",
    approach: "I modeled the domain first — activity, organization, profile, unit, and course entities — then built the ETL layer around those relationships so the output tables matched how analysts actually think.",
    deliverables: "Python ETL scripts, Tableau-ready relational tables, bridge tables, validation reports, archived refreshes, and documented data model guidance.",
    process: [
      { label: "UNDERSTAND THE SOURCE", body: "I mapped Collaboratory's export structure before writing a single line of transformation code." },
      { label: "MODEL THE DOMAIN", body: "I designed relational tables that reflect how the data is actually used in Social Embeddedness reporting." },
      { label: "BUILD FOR TRUST", body: "Validation reports and quality checks are built in so stakeholders know when something has changed." },
      { label: "LEAVE IT RUNNABLE", body: "The pipeline is documented and structured so the team can refresh and archive reports without me in the room." },
    ],
    skills: ["Python", "ETL", "Tableau", "Data Modeling", "SQL", "Data Validation", "Documentation"],
    certificate: null,
    quote: null,
  },
  {
    slug: "hitachi-power-bi-dashboards",
    number: "03",
    title: "Enterprise QEI & Audit KPI Dashboards",
    org: "Hitachi Digital Services",
    date: "2022 – 2025",
    feedback: "+30% efficiency",
    teaser: "Power BI dashboards that made global audit and quality data visible and actionable for leadership teams.",
    lead: "Audit data was scattered across regions. I built a reporting layer that surfaced the right KPIs to the right people and helped raise process efficiency by 30%.",
    collaboratedWith: "QEI & Audit Teams, Hitachi Digital Services",
    guidedBy: "Regional Leadership",
    rating: "30% process efficiency gain",
    approach: "I worked with audit and quality teams to understand what leadership actually needed to see, then designed Power BI reports that answered those questions without requiring data literacy from the reader.",
    deliverables: "Power BI dashboards for QEI and audit KPIs, regression and trend analysis models, automated Power Automate reporting pipelines, and monthly leadership report templates.",
    process: [
      { label: "LISTEN TO THE AUDIENCE", body: "I talked to audit and quality stakeholders to learn what decisions they needed the data to support." },
      { label: "CLEAN AND STRUCTURE", body: "I prepared and validated large datasets in Python, SQL, and Excel before any visualization work." },
      { label: "BUILD THE SIGNAL", body: "I used regression and trend analysis to surface compliance patterns and reduce prediction errors by 20%." },
      { label: "AUTOMATE THE LOOP", body: "I used Power Automate to distribute updated reports to stakeholders on schedule, removing the manual step." },
    ],
    skills: ["Power BI", "Python", "SQL", "Excel", "Power Automate", "Regression Analysis", "Data Validation"],
    certificate: null,
    quote: null,
  },
  {
    slug: "iisc-ball-tracking",
    number: "04",
    title: "Ball-Tracking Computer Vision Application",
    org: "Indian Institute of Science",
    date: "Jan – Jul 2022",
    feedback: "Research",
    teaser: "A smartphone-based ball-tracking system using annotated video pipelines and Python visualization tools.",
    lead: "This is where I learned that the quality of your training data determines everything downstream. Careful preparation here turned raw video into a model that could actually track motion reliably.",
    collaboratedWith: "Research Lab, IISc Bengaluru",
    guidedBy: "IISc Research Supervisors",
    rating: "Research project",
    approach: "I built the data annotation and preprocessing pipeline from the ground up, then used Python visualization to make the model's trajectory predictions interpretable for research stakeholders.",
    deliverables: "Ball-tracking application, annotated data pipelines, Matplotlib and Seaborn trajectory visualizations, cleaned and validated datasets, and a documented methodology report.",
    process: [
      { label: "CAPTURE AND ANNOTATE", body: "I designed a smartphone video capture workflow and built annotation pipelines to generate labeled training data." },
      { label: "CLEAN FOR RELIABILITY", body: "I managed preprocessing and validation steps that reduced noise and made the model's training data consistent." },
      { label: "EXPLORE THE PATTERNS", body: "I used EDA to uncover motion patterns in the dataset and guide model improvements." },
      { label: "MAKE IT EXPLAINABLE", body: "I used Matplotlib and Seaborn to visualize trajectory predictions so research stakeholders could evaluate and discuss the results." },
    ],
    skills: ["Python", "Matplotlib", "Seaborn", "Computer Vision", "EDA", "Data Annotation", "Research"],
    certificate: null,
    quote: null,
  },
];
